forge 'https://forge.puppet.com'

mod 'puppet-nginx',                 '1.1.0'
mod 'puppetlabs-apt',               '7.3.0'
mod 'puppetlabs-concat',            '6.2.0'
mod 'puppetlabs-facts',             '1.0.0'
mod 'puppetlabs-inifile',           '4.1.0'
mod 'puppetlabs-postgresql',        '6.3.0'
mod 'puppetlabs-puppet_agent',      '3.0.2'
mod 'puppetlabs-stdlib',            '6.2.0'
mod 'puppetlabs-translate',         '2.1.0'
